### ISSUE TITLE
获取数据失败

### ISSUE THREAD

**Issue by zuolingfeng** [XueSeason/Generate-QRCode-BarCode-iOS#1]
点击点击获取虚拟会员卡，弹出获取数据失败-无法连接到服务器

**Comment by XueSeason** [comment]
这个数据是从本地基于node搭建的后台获取到的。请保证具备node和express的运行环境。
node后台的代码在VMC目录下。

**Comment by zuolingfeng** [comment]
能不能在README.md里把后台搭建的一些相关资料也加上去。我刚看README.md，完全没有提到，所以也没有注意到需要本地搭建后台。。

**Comment by zuolingfeng** [comment]
能不能在README.md里把后台搭建的一些相关步骤也加上去

**Comment by XueSeason** [comment]
后台搭建因为平台不同，步骤也会不同，所占篇幅会很多，而且搭建过程网上很多，没必要写在README中，毕竟这不是一个node+express的环境搭建教程。  
不过可以参考这篇文章 http://finalhome.org/2014/05/19/Nodejs/%E6%90%AD%E5%BB%BANode+Express+Mongodb%E7%8E%AF%E5%A2%83/
里面的数据库MongoDB的搭建可以跳过。

**Comment by zuolingfeng** [comment]
多谢了。我的意思就是这样，可以给个node+express的环境搭建教程URL。免得我们多走弯路
